Travel.create([{ n_perusahaan: "PT. CIPAGANTI CITRA NUGRAHA" , alamat:" Jl. Gatot Subroto, Bandung",                    jumlah: 262 ,  n_travel: "Cipaganti",   n_img: "https://i.imgur.com/tpEGKtv.jpg",   deskripsi: " Irure ut reprehenderit duis id id esse ad. Aute qui laboris eu officia laboris consectetur quis id pariatur est exercitation. Deserunt ullamco fugiat laboris laboris fugiat et qui occaecat dolore laboris.

Duis ipsum adipisicing et esse aliquip non id ullamco. Est et dolore cupidatat tempor nostrud sint elit ad laboris ad duis sunt. Ea velit aliqua culpa in ipsum minim est dolor. Aliqua aliquip est nisi culpa sunt ipsum elit labore non labore nisi quis.

Irure et ad pariatur qui esse elit ut. Eiusmod fugiat veniam incididunt et. Fugiat et non id consectetur ullamco. Amet et cillum tempor culpa esse anim proident tempor et elit laborum.

Reprehenderit cupidatat elit proident non. In consectetur proident ut cillum Lorem. Culpa aute aliquip magna sunt proident qui incididunt. Nostrud eu in veniam elit reprehenderit deserunt et enim et duis quis consectetur minim. Excepteur aliquip esse ullamco ipsum enim elit occaecat cupidatat. Ex culpa esse sint velit."}])
Travel.create([{ n_perusahaan: "PT. BATARA TITIAN KENCANA",    alamat:" Jl. Cihampelas Bandung",                        jumlah: 110,   n_travel: "X Trans",     n_img: "https://i.imgur.com/JJg7WBK.jpg",   deskripsi: " Velit enim aliqua tempor magna dolore est et excepteur dolor. Quis commodo cillum sint ex. Commodo occaecat aliqua culpa sunt anim commodo magna ex id. Ex minim et sint aliqua velit reprehenderit nisi voluptate ex velit qui veniam enim amet. Quis qui ut dolor non Lorem labore esse sint culpa.

Tempor minim Lorem amet mollit sunt veniam laboris ut excepteur. Velit sunt eu nostrud veniam. Veniam ipsum non officia ea ex aliqua eiusmod qui voluptate ullamco aute magna.

Id commodo elit tempor non laborum irure voluptate incididunt pariatur est. Id minim adipisicing non dolore cillum ipsum qui occaecat dolore pariatur anim. Dolore in cillum Lorem labore mollit mollit qui. Ex nostrud veniam nulla et consequat velit sit anim nisi laboris amet non ex amet.

Laborum cupidatat id esse in eiusmod est laboris incididunt non ut sunt dolore non. Et velit nostrud excepteur reprehenderit aliquip velit. Fugiat consectetur Lorem excepteur minim consequat. Consectetur culpa deserunt aliquip consectetur dolore cupidatat nostrud officia adipisicing culpa velit elit. Labore in do in pariatur enim minim."}])
Travel.create([{ n_perusahaan: "PT. NURRACHMADI BERSAMA",      alamat:" jl. Surapati",                                  jumlah: 60,    n_travel: "Baraya",      n_img: "https://i.imgur.com/otXdBBZ.jpg",   deskripsi: " Sint cillum dolor non velit commodo. Eu ex irure minim sit labore anim do ullamco laborum culpa id adipisicing culpa. Eu nisi consequat et dolor amet incididunt amet id amet sint irure nisi. Excepteur amet irure culpa cupidatat nulla cupidatat consectetur ex. Occaecat est dolore et in ea ex in tempor nisi in proident aliqua.

Occaecat velit nisi culpa nulla nulla enim proident aliquip ex sunt eu tempor aute. Anim esse officia voluptate commodo tempor laborum nisi veniam qui dolore enim quis. Irure do aliqua velit laborum irure officia do occaecat do id ullamco do. Anim elit ea consectetur ipsum do magna quis.

Esse id qui quis eiusmod aliqua ipsum enim irure est ullamco incididunt ut Lorem id. Quis cupidatat voluptate laborum veniam nulla est consectetur laboris esse ullamco. Aliqua proident sunt ex pariatur velit ullamco voluptate cillum tempor ad labore ad quis velit.

Deserunt in Lorem ea qui dolore. Voluptate duis nulla mollit ad fugiat occaecat consequat. Proident eu aliqua id culpa fugiat commodo exercitation deserunt dolor ipsum nulla nostrud proident. Qui amet nostrud excepteur ex laboris labore. Eu officia eu esse ut ad. Do irure laboris do est nisi irure ipsum exercitation."}])
Travel.create([{ n_perusahaan: "PT. VETIGA NADI",              alamat:" jl. Gatot Subroto, Bandung",                    jumlah: 68,    n_travel: "V 3 Trans",   n_img: "https://i.imgur.com/iWcMSqG.jpg",   deskripsi: " Est cillum anim eu elit voluptate quis. Ad esse labore laboris non ullamco. Anim aute ex incididunt exercitation laborum reprehenderit.

Id ipsum amet adipisicing occaecat Lorem duis ullamco pariatur exercitation nulla excepteur irure laborum occaecat. Laborum proident elit ut esse reprehenderit qui. Enim esse proident aliqua consequat culpa adipisicing reprehenderit. Fugiat cillum esse ut minim irure id.

Duis ipsum sunt nostrud cupidatat veniam. Occaecat esse aliqua ex dolore id laborum sunt. Officia anim ad adipisicing amet irure cillum eu pariatur ut eiusmod ullamco ea culpa. Incididunt officia ut laborum duis id dolor culpa nulla cillum ullamco Lorem mollit reprehenderit. Labore enim excepteur deserunt elit quis tempor fugiat reprehenderit. Laborum velit sint id exercitation voluptate adipisicing dolore.

Anim Lorem anim velit culpa veniam tempor nulla ea pariatur enim irure culpa velit velit. Id sint ad eu mollit. Et exercitation amet exercitation est."}])
Travel.create([{ n_perusahaan: "PT. METROMODA TRAVELATAMA",    alamat:" Jl. Pasir Kaliki No. 15",                       jumlah: 9,     n_travel: "Travelatama", n_img: "https://i.imgur.com/7Ey5odY.jpg",   deskripsi: " Et ullamco ullamco tempor enim occaecat qui adipisicing pariatur enim esse proident aute officia. Sit velit dolor est culpa in et incididunt id nulla sunt. Dolore officia consectetur cillum commodo eu qui. Amet dolor magna et ipsum dolore cillum ea eu sint aliquip. Qui ullamco magna officia consectetur culpa irure sunt enim aliqua culpa nulla cillum consequat nostrud.

Non magna elit sit sit ad esse laborum enim sint nostrud cupidatat reprehenderit. Mollit cillum pariatur deserunt adipisicing commodo non aliquip enim. Sit fugiat sit quis consequat anim tempor qui. Velit consequat anim duis ea cillum ex aute.

Reprehenderit ipsum Lorem minim tempor voluptate. Incididunt veniam in aliqua ea labore nisi cupidatat voluptate cupidatat fugiat ea. Dolor incididunt nostrud enim consequat deserunt cillum do Lorem quis culpa mollit est dolor. Pariatur veniam ea dolore ullamco anim commodo aliqua tempor consectetur. Aute nostrud veniam veniam duis velit exercitation laboris nostrud amet nulla. Dolor occaecat labore fugiat ex sit exercitation anim ex laboris.

Sunt minim sunt quis deserunt. Ut mollit labore ut minim tempor. Eu eiusmod Lorem et nulla excepteur ut anim sit nulla nulla eu non pariatur. Fugiat ullamco aliquip ex anim dolor est sunt anim do laborum tempor quis quis occaecat. Ad nostrud qui quis irure aute laboris fugiat eu nulla nulla incididunt minim dolore. Occaecat consectetur officia eu ipsum voluptate mollit culpa. Commodo officia non irure nisi culpa velit incididunt nisi velit occaecat deserunt."}])
Travel.create([{ n_perusahaan: "PT. PURABAYA PANCASAKTI",      alamat:" Jl. Babakan Sari II No. 10 Kota. Bandung",      jumlah: 26,    n_travel: "Panca",       n_img: "https://i.imgur.com/MPOKCED.jpg",   deskripsi: " Id esse exercitation ullamco laborum elit fugiat aliqua minim pariatur in. Irure ipsum tempor ex anim velit in laborum occaecat nisi ipsum minim culpa duis ea. Mollit dolore ipsum dolor aliquip et elit nostrud dolor amet proident adipisicing sit deserunt. Incididunt magna consequat ex excepteur commodo excepteur nulla exercitation qui officia minim officia velit. Dolore ipsum esse dolor in ex eiusmod mollit ea veniam. Est nisi ipsum anim consectetur nostrud dolor adipisicing ullamco. Ut aliqua proident officia commodo et commodo laboris Lorem laborum.

Sit tempor culpa et ipsum fugiat sit duis quis. Cupidatat eu laboris eu irure sint laborum ipsum. Et dolor pariatur non qui velit qui culpa commodo tempor proident voluptate proident veniam.

Deserunt fugiat culpa ex officia aute laboris veniam fugiat cillum ea duis id. Duis eiusmod excepteur nostrud adipisicing ex ullamco veniam. Occaecat duis adipisicing commodo ullamco ipsum occaecat incididunt nostrud pariatur eu.

Nulla laboris duis et elit occaecat. Esse magna velit adipisicing pariatur consequat voluptate elit mollit commodo occaecat nulla exercitation. Nulla ipsum exercitation incididunt sunt nulla in cillum. Minim esse ad irure pariatur irure aliquip ullamco sint elit eiusmod sit veniam minim velit. Fugiat pariatur aliquip minim pariatur reprehenderit exercitation voluptate minim cillum duis."}])
Travel.create([{ n_perusahaan: "PT. TRANSLINE",                alamat:" Jl. Surya Sumantri No. 86 Kota. Bandung",       jumlah: 16,    n_travel: "Transline",   n_img: "https://i.imgur.com/WU3JCTj.jpg",   deskripsi: " Duis mollit ipsum voluptate sint eiusmod tempor. Do fugiat magna velit exercitation. Ad sint dolor officia esse labore elit qui. Lorem exercitation culpa et ad dolor reprehenderit excepteur. Elit minim mollit adipisicing laboris laborum ad commodo voluptate irure. Amet proident aliquip consequat nulla cupidatat. Dolor aute qui ut laboris dolor aliquip.

Sit sint officia incididunt minim elit ut non ea aute et excepteur tempor. Consectetur magna quis esse aliqua mollit minim. Mollit laboris ea in duis nostrud est voluptate culpa.

Eu esse qui consequat laboris aliqua sint id irure adipisicing. Sint aliqua elit occaecat laboris adipisicing minim do minim sint exercitation nulla incididunt. Culpa mollit amet sit eu veniam elit. Id mollit sunt sunt velit occaecat magna fugiat ad adipisicing consectetur. Ut mollit Lorem esse ipsum aliquip. Reprehenderit velit labore fugiat ipsum. Elit fugiat dolor aute enim do exercitation consequat aute do ex ipsum.

Eiusmod incididunt nostrud ut adipisicing fugiat enim ex. Commodo nisi aliquip aliquip ut dolor commodo ipsum minim cupidatat tempor. Ullamco do velit culpa amet veniam dolor commodo."}])
Travel.create([{ n_perusahaan: "PT. HERI SURYA PUTRA",         alamat:" jl. Cihampelas",                                jumlah: 10,    n_travel: "Transpoter",  n_img: "https://i.imgur.com/tpEGKtv.jpg",   deskripsi: " Qui consequat dolore amet labore occaecat dolore consequat Lorem. Ex nisi occaecat occaecat sint duis officia nisi sit exercitation eiusmod sit sit enim eu. Nisi tempor proident laboris nisi sint velit laboris eu dolore mollit. Nulla in aute duis culpa adipisicing amet nulla.

Esse ut in amet ullamco esse nostrud ullamco culpa incididunt aliqua. Aliquip culpa commodo occaecat non reprehenderit nostrud ut adipisicing consectetur. Nostrud incididunt deserunt enim nulla ipsum amet duis. Voluptate magna Lorem non minim quis Lorem consectetur nostrud amet duis sit ut. Veniam reprehenderit aute voluptate fugiat pariatur sint aliqua. Sunt incididunt do Lorem reprehenderit occaecat. Ut aliqua dolor sit sunt aute deserunt elit cupidatat enim commodo cupidatat.

Tempor fugiat nulla fugiat qui pariatur eiusmod qui nisi. Sit nulla ea eiusmod id minim labore laboris veniam. Laborum deserunt sit ut consequat dolor officia excepteur nostrud occaecat id veniam non. Lorem aliquip qui nulla voluptate enim enim duis irure est deserunt eiusmod velit enim.

Consequat sint eiusmod enim magna anim proident officia aliqua et. Adipisicing id pariatur est culpa magna ex. Reprehenderit magna exercitation nulla deserunt velit elit culpa id. Consequat minim sint laboris et aute. Nisi ut magna qui tempor esse incididunt nisi nisi. Pariatur est occaecat ad proident laboris id duis occaecat qui cillum. Aliquip eiusmod duis officia eu laboris Lorem dolor nostrud proident eu nisi nostrud."}])
Travel.create([{ n_perusahaan: "CV. CITRA TIARA TRANSPORT",    alamat:" Jl. Dipati Ukur No. 53",                        jumlah: 75,    n_travel: "City Trans",  n_img: "https://i.imgur.com/JJg7WBK.jpg",   deskripsi: " Quis culpa occaecat mollit consequat exercitation consectetur incididunt duis id aliquip dolore mollit nulla excepteur. Voluptate in et Lorem nostrud voluptate ipsum. Sit sunt in ullamco reprehenderit consequat sunt commodo cillum eu commodo. Esse deserunt sunt consequat minim deserunt.

Incididunt do occaecat consequat aute ad ad cillum laborum magna excepteur nostrud ea. Esse officia officia enim cupidatat id. Qui minim id sunt veniam in culpa aliquip et commodo.

Amet fugiat Lorem excepteur et magna Lorem ullamco tempor exercitation pariatur consectetur anim. Pariatur eiusmod elit sit deserunt quis elit. Anim adipisicing dolore Lorem velit eu officia. Minim mollit culpa enim incididunt velit cillum culpa sint in deserunt. Laboris excepteur mollit ea dolore occaecat voluptate in reprehenderit cupidatat duis consectetur. Labore id ex deserunt officia id amet reprehenderit sint est labore quis exercitation in sit. Aliquip dolore deserunt sint aute deserunt ipsum eu reprehenderit quis consequat magna nulla veniam.

Magna laboris sit ut exercitation labore sit. Aute labore aute ut sit amet duis nostrud officia mollit dolor duis dolor velit. Lorem consectetur voluptate do ad sint tempor elit ipsum anim nisi. Labore tempor adipisicing ex non dolor exercitation aliqua magna duis. Aute ex labore fugiat est duis sunt ullamco sint. In aliqua culpa anim aliqua magna ad magna non duis cupidatat minim. Ipsum aliquip excepteur irure ex incididunt consectetur."}])
Travel.create([{ n_perusahaan: "CV. PANCA JAYA UTAMA",         alamat:" Komplek Banyubiru Blok C  Kota. Bandung",       jumlah: 10,    n_travel: "Panca",       n_img: "https://i.imgur.com/otXdBBZ.jpg",   deskripsi: " Consectetur nulla ad eu est exercitation anim. Ea labore consectetur velit ex ad sunt culpa cupidatat cillum. Excepteur exercitation dolor culpa nisi velit voluptate sunt do veniam. Fugiat culpa voluptate do occaecat excepteur.

Veniam amet fugiat sit cillum qui et occaecat. Tempor reprehenderit nisi incididunt elit pariatur proident in dolore. Pariatur aute ea eu occaecat cillum in magna ea.

Consectetur dolore amet eu nulla proident qui laboris proident mollit culpa eiusmod est. Minim sit culpa amet fugiat adipisicing veniam culpa reprehenderit velit dolor reprehenderit. Nisi est ut consectetur commodo consequat minim.

Ullamco culpa irure occaecat tempor do fugiat sint ipsum incididunt consectetur enim anim. Cillum officia laborum consectetur duis occaecat do officia ex. Eu consequat reprehenderit proident culpa aliqua elit. Pariatur ut mollit nostrud qui incididunt nisi nulla do enim enim est. Consequat in commodo officia adipisicing elit et. Irure dolor esse esse excepteur tempor non qui pariatur do."}])
Travel.create([{ n_perusahaan: "PT. LINTAS MEDIA KARYA",       alamat:" Jl. Otto Iskandardinata No. 17 Kota. Bandung",  jumlah: 10,    n_travel: "LINKAR",      n_img: "https://i.imgur.com/iWcMSqG.jpg",   deskripsi: " Sunt ea laborum sint eiusmod voluptate occaecat consectetur cupidatat ut. Eiusmod ad cupidatat laboris adipisicing excepteur est amet laborum velit do in nulla. Et sit labore minim adipisicing officia adipisicing qui nostrud excepteur sit. Aute aliquip non eu excepteur.

Sit ullamco commodo minim veniam proident. Elit magna deserunt dolore culpa anim ad ad aute minim. Magna adipisicing id sunt qui sunt do pariatur in non.

Nisi cupidatat velit esse occaecat anim duis mollit elit magna occaecat in labore dolore. Consectetur id minim proident voluptate cillum deserunt adipisicing deserunt. Duis amet excepteur aute tempor id eiusmod proident enim. Qui qui dolore qui enim culpa ea ut cillum consectetur quis aliquip est esse. Enim esse reprehenderit enim duis laboris duis cupidatat anim. Nulla pariatur magna veniam magna sunt irure dolor cupidatat id adipisicing veniam veniam.

Duis culpa voluptate incididunt elit. Quis velit ex esse ipsum aliquip magna aliquip duis deserunt Lorem. Id in minim nisi voluptate Lorem et. Commodo non ullamco officia nisi nisi nostrud aute nulla aliqua esse aliquip deserunt. Nostrud laboris adipisicing non dolor."}])
Travel.create([{ n_perusahaan: "PT. DAY TRANS",                alamat:" jl. Cihampelas",                                jumlah: 70,    n_travel: "Day Trans",   n_img: "https://i.imgur.com/7Ey5odY.jpg",   deskripsi: " Eiusmod ut culpa tempor consequat laborum amet eiusmod mollit aute sint tempor reprehenderit ipsum. Pariatur Lorem proident esse laboris pariatur do adipisicing occaecat. Non aliqua cupidatat esse aliquip quis. Elit aliquip veniam id exercitation in est culpa laborum consequat consectetur. Exercitation proident dolore incididunt fugiat nostrud commodo. Pariatur nulla excepteur aliqua sint.

Ex aute irure enim laborum et minim deserunt laboris nulla exercitation. Nulla aliqua aliquip commodo ad quis dolor voluptate est velit. Velit cupidatat mollit esse incididunt ad sit fugiat deserunt reprehenderit. Excepteur voluptate laborum amet esse qui laboris magna sint dolor occaecat consequat voluptate Lorem.

Esse qui consectetur occaecat fugiat incididunt incididunt proident voluptate sit veniam velit culpa ea. Ea dolor commodo sunt culpa eiusmod eiusmod ea. Ea qui tempor tempor amet amet adipisicing qui esse. Consequat nisi laboris tempor anim. Quis quis esse sunt sit anim minim et nostrud consequat laborum. Magna nulla nostrud consequat officia laborum sunt aliqua exercitation.

Quis laboris non consectetur elit irure amet incididunt eiusmod duis mollit est Lorem deserunt. Cillum incididunt elit aliquip aute nostrud consectetur cillum sunt. Labore do tempor amet culpa reprehenderit incididunt excepteur exercitation commodo. Aute ut ut esse velit."}])
Travel.create([{ n_perusahaan: "PT. STAR LINE",                alamat:" Ruko MTC Blok. I No. 5 Margahayu Raya",         jumlah: 14,    n_travel: "Star Line",   n_img: "https://i.imgur.com/MPOKCED.jpg",   deskripsi: " Consectetur ullamco cupidatat laboris quis aute adipisicing cillum. Do qui dolore mollit aute adipisicing amet veniam velit pariatur in sunt tempor. Nisi ad est deserunt culpa deserunt Lorem esse elit magna. Anim laborum minim mollit irure elit elit tempor officia amet occaecat aliqua deserunt laboris. Qui sint cillum ad nulla occaecat ea voluptate laborum nostrud amet.

Do sunt laborum aliquip ad cillum tempor laboris enim culpa incididunt incididunt tempor. Voluptate est cillum mollit ut nostrud. Velit deserunt laboris ut in sint nisi ut id. Consectetur voluptate aute adipisicing id mollit ex non laboris eu incididunt culpa deserunt est dolor. Occaecat amet tempor tempor veniam ad velit eiusmod incididunt ea.

Laborum esse anim irure excepteur consectetur eu proident labore esse duis eu. Consequat esse officia ex eiusmod pariatur amet minim nostrud officia nulla duis sunt do est. Ea incididunt do deserunt qui nostrud eiusmod et in pariatur eu id minim mollit. Irure non aute proident magna non quis elit magna deserunt. Officia veniam est ad commodo sit laboris sint et. Aliquip in ullamco mollit magna proident reprehenderit laboris mollit exercitation. Mollit sint laboris consectetur occaecat commodo excepteur eiusmod sit aute cillum anim Lorem veniam.

Excepteur elit dolore eu anim. Officia sint nostrud officia eiusmod ex enim nostrud minim sint consequat sint mollit labore anim. Magna fugiat in duis qui incididunt. Excepteur ad do culpa est enim ut fugiat minim. Deserunt reprehenderit aute esse labore voluptate id ullamco elit. Exercitation nulla do nulla officia et sunt irure consectetur in eiusmod minim. Aliquip mollit eu aute nostrud."}])
Travel.create([{ n_perusahaan: "PT. DISA PRATAMA MANDIRI",     alamat:" Jl. Soekarno Hatta No. 62 / 172 Kota Bandung",  jumlah: 10,    n_travel: "Primajasa",   n_img: "https://i.imgur.com/WU3JCTj.jpg",   deskripsi: " Id aute deserunt aute occaecat reprehenderit sunt officia adipisicing veniam adipisicing ut deserunt ea. Id sint reprehenderit do aute fugiat consectetur ex aliquip cillum exercitation aliqua mollit nostrud id. Proident deserunt magna nostrud non. Non eu mollit et adipisicing anim amet velit adipisicing adipisicing cupidatat ut ea.

Ad esse aliqua qui mollit nulla tempor quis deserunt ut occaecat enim minim. Consectetur Lorem veniam pariatur culpa. Mollit amet commodo ullamco cupidatat velit aliquip est ad eiusmod adipisicing sit. Sit excepteur ex et duis in tempor pariatur sunt. Dolor amet cupidatat anim incididunt consectetur eu laborum consectetur incididunt nulla velit irure eu. Sint est dolore elit est ullamco do ex ut enim. Tempor tempor id mollit et incididunt culpa ea laborum cillum nulla et culpa cillum.

Consequat id enim velit sit amet nisi nulla ipsum esse tempor. Aute qui excepteur aliqua labore ipsum sint culpa commodo cupidatat reprehenderit. Laborum fugiat magna reprehenderit esse. Irure deserunt officia qui anim aute cupidatat pariatur eiusmod proident ad. Dolor exercitation incididunt esse fugiat enim eu sunt culpa deserunt ullamco fugiat consectetur consequat. Mollit sit elit dolor culpa sint veniam est pariatur nulla minim cillum veniam commodo.

Velit ut excepteur magna quis ipsum nisi. Cupidatat esse voluptate qui nulla nulla mollit et proident in. Enim pariatur exercitation nostrud dolore sit enim laboris nisi ullamco. Cillum eu veniam aute ad dolore adipisicing. Nisi velit anim non excepteur adipisicing ex adipisicing ullamco sunt in elit qui nisi. Minim proident ex consectetur cupidatat sint anim elit esse."}])
Travel.create([{ n_perusahaan: "PT. TELE TRANS",               alamat:" Jl. Surapati, Dapenpos",                        jumlah: 5,     n_travel: "Tele Trans",  n_img: "https://i.imgur.com/iWcMSqG.jpg",   deskripsi: " Deserunt tempor id adipisicing magna ad do adipisicing sit consectetur officia. Fugiat deserunt mollit exercitation esse proident sint proident exercitation. Mollit reprehenderit qui consectetur elit velit id exercitation consectetur consequat anim laboris nisi fugiat laborum. Nisi consequat cillum eu ipsum eiusmod laboris amet est sunt dolore laboris proident occaecat eu.

Mollit duis deserunt eiusmod amet culpa in fugiat ullamco ea elit. Laboris nulla duis pariatur ad laboris dolore laborum adipisicing eu tempor qui. Quis nulla adipisicing tempor aliquip incididunt fugiat aliqua dolore consequat fugiat velit. Veniam aliqua velit pariatur irure do voluptate velit exercitation non aute amet. Anim incididunt culpa amet voluptate Lorem reprehenderit consectetur ex tempor do voluptate anim. Id eu ad amet proident ipsum amet ipsum nostrud tempor incididunt elit id nostrud nostrud.

Enim anim non minim velit dolore exercitation proident. Pariatur consectetur fugiat cupidatat quis ex minim ea ad elit. Do fugiat cillum aliqua cupidatat ullamco tempor amet non elit proident laboris.

Labore dolor nulla dolor cupidatat. Ad sit aute nisi eu in. Nulla ut amet est amet laboris deserunt excepteur nulla anim pariatur."}])
Travel.create([{ n_perusahaan: "PT. SARANA MARGABAKTI UTAMA",  alamat:" Jl. Buahbatu",                                  jumlah: 5,     n_travel: "Transtol",    n_img: "https://i.imgur.com/7Ey5odY.jpg",   deskripsi: " Mollit commodo cupidatat sit reprehenderit tempor fugiat. Enim aute est et Lorem eiusmod ea deserunt irure. Proident ipsum amet magna nisi nisi irure mollit ex aute. Minim id fugiat dolor cillum. Culpa aute occaecat in sint ea quis culpa.

Pariatur labore exercitation do adipisicing tempor eu anim cillum deserunt magna culpa sint cillum dolor. Qui occaecat nisi fugiat laboris consequat proident ipsum officia. Est excepteur aute veniam amet laboris aliqua ex aliquip aliqua.

Amet pariatur fugiat culpa qui pariatur. Ad nulla laboris ipsum tempor laborum laborum consectetur anim. Proident labore veniam enim qui cillum Lorem. Nisi ut adipisicing fugiat magna. Laboris duis ex sunt laboris officia non consectetur nisi exercitation ipsum quis dolor culpa fugiat.

Consectetur consequat dolore cupidatat laboris elit amet deserunt minim. Enim veniam nostrud amet incididunt. Dolor eiusmod ad tempor sit Lorem sit deserunt. Ex amet sit laboris proident commodo do nisi ut eiusmod sint. Adipisicing excepteur sint cillum ea fugiat ex do. Labore officia enim cillum do fugiat."}])
Travel.create([{ n_perusahaan: "CV. SAFA",                     alamat:" jl. Sethia Budi",                               jumlah: 14,    n_travel: "Safa Trans",  n_img: "https://i.imgur.com/MPOKCED.jpg",   deskripsi: " Excepteur consequat Lorem adipisicing ea. Amet adipisicing minim dolor occaecat ex eiusmod mollit incididunt voluptate duis magna. Sit excepteur pariatur anim excepteur anim ipsum labore proident. Enim id consequat adipisicing ullamco occaecat aliquip nisi ad consectetur irure. Aliqua magna proident ex irure. Amet proident ad incididunt ut ea esse.

Sunt reprehenderit irure cillum excepteur ad deserunt reprehenderit. Consequat sit in nisi est enim et minim sit consequat nisi voluptate. Et do proident eiusmod ex qui reprehenderit amet sunt proident cillum reprehenderit.

Id ullamco non aute irure excepteur nulla. Ipsum anim sunt laborum amet ea est irure enim fugiat sint commodo. Aute nulla ad voluptate ipsum. Amet dolore proident aliquip elit ea nisi quis. Aliquip ullamco sunt irure commodo ex occaecat dolor occaecat aute.

In proident ex reprehenderit amet consectetur dolor tempor aute deserunt culpa sunt. Tempor do laboris dolore proident elit aute sit. Tempor ad do culpa labore dolore officia nulla aute anim laboris. Occaecat ipsum ad est ea qui labore reprehenderit consequat. Excepteur in commodo culpa culpa amet ad occaecat nulla dolor veniam. Irure dolor minim excepteur et. Cupidatat sunt amet quis reprehenderit consequat in deserunt ullamco sunt."}])
Travel.create([{ n_perusahaan: "CV. 4848",                     alamat:" Jl. Kebon Kawung",                              jumlah: 5,     n_travel: "4848",        n_img: "https://i.imgur.com/WU3JCTj.jpg",   deskripsi: " Aute eu ex laborum tempor veniam ea consectetur aliquip nostrud esse cillum incididunt sit. Ullamco consequat eu id qui sint commodo tempor cupidatat officia id quis. Veniam consectetur duis sunt consequat tempor. Exercitation mollit sunt ut irure anim et nisi et adipisicing non eiusmod anim. In aliqua cillum nisi pariatur fugiat exercitation aliqua sunt id nisi voluptate aliqua. Adipisicing velit mollit incididunt eu.

Culpa eiusmod sit ad in. Lorem ad ullamco minim Lorem velit aute dolore ex magna veniam ex. Id id aliqua tempor adipisicing proident enim occaecat labore eiusmod reprehenderit minim pariatur aliquip occaecat. Quis magna incididunt velit proident eu.

Enim amet incididunt excepteur voluptate consectetur. Tempor anim incididunt est non excepteur Lorem Lorem do laborum laboris ea. Exercitation anim deserunt minim commodo do amet aute.

Non laborum duis Lorem do labore ea aute. Proident proident Lorem do aute cillum ullamco aute nulla anim culpa. Sunt adipisicing sunt incididunt do exercitation. Ipsum eu minim ea incididunt adipisicing. Aliqua dolore duis exercitation ex cupidatat dolor fugiat enim sunt esse officia consequat ipsum laborum. Labore occaecat quis duis quis sint anim."}])